version: '3'
services:
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    # ports:
    #   - "5432:5432"
    depends_on:
      - web

  web:
    build:
      context: .
    ports:
      - "3000:3000"
    entrypoint: ./docker-entrypoint.sh
    volumes:
      - .:/app
